"""empty message

Revision ID: 462a25f993dd
Revises: 
Create Date: 2022-05-09 23:14:13.301100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462a25f993dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dev_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dev_types')
    # ### end Alembic commands ###
